import type { Agent, Task, LogEntry, SystemStats } from './types.js';

const startTime = Date.now();

export const agents: Agent[] = [
  {
    id: 'slippery-jim',
    name: 'James Bolivar DiGriz',
    codename: 'SLIPPERY JIM',
    role: 'Master Infiltrator',
    status: 'working',
    avatar: '🐀',
    color: '#00ff88',
    position: { x: 35, y: 40 },
    currentTask: 'Analyzing Inskipp security protocols',
    tasksCompleted: 247,
    uptime: 86400 * 3,
    specializations: ['infiltration', 'social-engineering', 'code'],
    memoryUsed: 512,
    cpuLoad: 78,
  },
  {
    id: 'angelina',
    name: 'Angelina',
    codename: 'ANGEL',
    role: 'Tactical Specialist',
    status: 'chatting',
    avatar: '👼',
    color: '#00d4ff',
    position: { x: 55, y: 30 },
    currentTask: 'Coordinating extraction plan',
    tasksCompleted: 189,
    uptime: 86400 * 2,
    specializations: ['tactics', 'weapons', 'analysis'],
    memoryUsed: 384,
    cpuLoad: 45,
  },
  {
    id: 'inskipp',
    name: 'Harold Peters Inskipp',
    codename: 'THE CHIEF',
    role: 'Command & Control',
    status: 'working',
    avatar: '🎖️',
    color: '#ff8c00',
    position: { x: 70, y: 55 },
    currentTask: 'Reviewing mission reports',
    tasksCompleted: 412,
    uptime: 86400 * 7,
    specializations: ['command', 'strategy', 'intelligence'],
    memoryUsed: 768,
    cpuLoad: 62,
  },
  {
    id: 'meta-llc',
    name: 'META-LCC',
    codename: 'GHOST',
    role: 'Recon & SIGINT',
    status: 'idle',
    avatar: '👁️',
    color: '#8888ff',
    position: { x: 20, y: 65 },
    currentTask: undefined,
    tasksCompleted: 93,
    uptime: 86400,
    specializations: ['recon', 'surveillance', 'decrypt'],
    memoryUsed: 256,
    cpuLoad: 12,
  },
  {
    id: 'bishop',
    name: 'Bishop-7',
    codename: 'BISHOP',
    role: 'Deep Research',
    status: 'working',
    avatar: '♟️',
    color: '#00d4ff',
    position: { x: 48, y: 70 },
    currentTask: 'Cross-referencing galactic databases',
    tasksCompleted: 156,
    uptime: 86400 * 4,
    specializations: ['research', 'write', 'analyze'],
    memoryUsed: 640,
    cpuLoad: 88,
  },
  {
    id: 'razor',
    name: 'Razor-9',
    codename: 'RAZOR',
    role: 'Code & Exploit',
    status: 'error',
    avatar: '⚔️',
    color: '#ff3366',
    position: { x: 82, y: 25 },
    currentTask: 'Runtime exception in payload delivery',
    tasksCompleted: 71,
    uptime: 3600 * 6,
    specializations: ['exploit', 'code', 'breach'],
    memoryUsed: 320,
    cpuLoad: 5,
  },
];

export const tasks: Task[] = [
  {
    id: 't-001',
    title: 'Infiltrate Inskipp Financial Records',
    description: 'Obtain financial transaction logs from Special Corps HQ without triggering alarms.',
    status: 'running',
    priority: 'critical',
    type: 'infiltrate',
    assignedTo: 'slippery-jim',
    createdAt: Date.now() - 3600000,
    startedAt: Date.now() - 1800000,
    progress: 67,
    tags: ['ops', 'finance', 'stealth'],
    output: 'Access level 3 achieved. Proceeding to archive level...',
  },
  {
    id: 't-002',
    title: 'Analyze Morality Board Communications',
    description: 'Deep scan of Morality Board encrypted comms for extraction of actionable intel.',
    status: 'running',
    priority: 'high',
    type: 'analyze',
    assignedTo: 'bishop',
    createdAt: Date.now() - 7200000,
    startedAt: Date.now() - 5400000,
    progress: 44,
    tags: ['intel', 'decrypt', 'morality-board'],
  },
  {
    id: 't-003',
    title: 'Extraction Route Planning',
    description: 'Calculate optimal escape routes from Liokukae prison colony.',
    status: 'running',
    priority: 'critical',
    type: 'research',
    assignedTo: 'angelina',
    createdAt: Date.now() - 900000,
    startedAt: Date.now() - 600000,
    progress: 82,
    tags: ['escape', 'tactical', 'liokukae'],
  },
  {
    id: 't-004',
    title: 'Write Cover Identity: "Harold Resterbrook"',
    description: 'Full cover identity package including background history, credentials, implanted records.',
    status: 'queued',
    priority: 'high',
    type: 'write',
    createdAt: Date.now() - 600000,
    progress: 0,
    tags: ['identity', 'cover', 'docs'],
  },
  {
    id: 't-005',
    title: 'Monitor Corps Communication Channels',
    description: 'Continuous passive monitoring of Special Corps encrypted comms. Flag anomalies.',
    status: 'paused',
    priority: 'normal',
    type: 'monitor',
    assignedTo: 'meta-llc',
    createdAt: Date.now() - 86400000,
    startedAt: Date.now() - 43200000,
    progress: 30,
    tags: ['surveillance', 'sigint'],
  },
  {
    id: 't-006',
    title: 'Crack Vault-7 Access Protocol',
    description: 'Exploit CVE in legacy vault firmware.',
    status: 'failed',
    priority: 'high',
    type: 'code',
    assignedTo: 'razor',
    createdAt: Date.now() - 21600000,
    startedAt: Date.now() - 18000000,
    completedAt: Date.now() - 3600000,
    progress: 23,
    tags: ['exploit', 'vault', 'breach'],
    output: 'FATAL: Intrusion detection triggered at layer 4. Agent terminated.',
  },
  {
    id: 't-007',
    title: 'Research Bishwanath Currency Exchange',
    description: 'Map all known currency laundering nodes in the Outer Worlds financial network.',
    status: 'done',
    priority: 'normal',
    type: 'research',
    assignedTo: 'inskipp',
    createdAt: Date.now() - 172800000,
    startedAt: Date.now() - 168000000,
    completedAt: Date.now() - 86400000,
    progress: 100,
    tags: ['finance', 'research', 'outer-worlds'],
    output: '47 nodes identified. Full report uploaded to Intel base.',
  },
];

export const log: LogEntry[] = [
  { id: 'l-001', timestamp: Date.now() - 30000,  agentId: 'slippery-jim', agentName: 'SLIPPERY JIM', type: 'action',  content: 'Bypassed level-3 security checkpoint. Proceeding to archive.' },
  { id: 'l-002', timestamp: Date.now() - 65000,  agentId: 'bishop',       agentName: 'BISHOP',       type: 'action',  content: 'Decoded 14 encrypted messages. Cross-reference in progress.' },
  { id: 'l-003', timestamp: Date.now() - 90000,  agentId: 'angelina',     agentName: 'ANGEL',        type: 'message', content: 'Route Alpha confirmed viable. Route Beta under analysis.' },
  { id: 'l-004', timestamp: Date.now() - 120000, agentId: 'razor',        agentName: 'RAZOR',        type: 'error',   content: 'EXCEPTION: IntrusionDetection triggered. Aborting task t-006.' },
  { id: 'l-005', timestamp: Date.now() - 180000, agentId: 'meta-llc',     agentName: 'GHOST',        type: 'warning', content: 'Corps communication spike detected. Monitoring paused per protocol.' },
  { id: 'l-006', timestamp: Date.now() - 240000, agentId: 'inskipp',      agentName: 'THE CHIEF',    type: 'system',  content: 'Mission t-007 marked COMPLETE. Report archived.' },
];

export let completedToday = 12;

export function getStats(): SystemStats {
  const active  = agents.filter((a) => a.status !== 'offline').length;
  const memUsed = agents.reduce((sum, a) => sum + a.memoryUsed, 0);
  const avgCpu  = agents.reduce((sum, a) => sum + a.cpuLoad, 0) / agents.length;

  return {
    activeAgents:   active,
    totalAgents:    agents.length,
    runningTasks:   tasks.filter((t) => t.status === 'running').length,
    queuedTasks:    tasks.filter((t) => t.status === 'queued').length,
    completedToday,
    systemLoad:     Math.round(avgCpu),
    memoryTotal:    4096,
    memoryUsed:     memUsed,
    uptime:         Math.floor((Date.now() - startTime) / 1000) + 86400 * 3,
  };
}

export function addLog(entry: Omit<LogEntry, 'id' | 'timestamp'>): LogEntry {
  const full: LogEntry = { ...entry, id: `l-${Date.now()}`, timestamp: Date.now() };
  log.unshift(full);
  if (log.length > 200) log.pop();
  return full;
}
